name: Publish Docker image
on:
  push:
  schedule:
    - cron:  '2 0 * * 0'

jobs:
  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Convert repo to lower case for docker
        id: string_repo
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: linux/arm/v7,linux/arm/v6,linux/arm64,linux/386,linux/amd64
          pull: true
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/teeworlds-server:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
